### PR TITLE
✨ feat(calendar): expand the year range using the min and max date validators

### LINKED ISSUE #346: [Bug] z-date-picker cannot be used with Reactive Forms
## 🐞 Bug Description

`z-date-picker` **cannot be used with Reactive Forms (`formControlName`)** because it does **not provide a `ControlValueAccessor`**, causing Angular to throw the error:

> `NG01203: No value accessor for form control name: 'date'`

This means Angular does not know how to read/write values to the component when used in a reactive form.

## Steps to Reproduce

1. Create a reactive form with a `FormGroup` containing a `date` control.
2. Add `<z-date-picker formControlName="date"></z-date-picker>` inside the form.
3. Run the application.
4. Observe Angular throwing the following error at runtime.

## Expected Behavior

`z-date-picker` should behave as a fully supported Angular form control:

* Accept `formControlName`
* Update the form when the user picks a date
* Reflect changes from the form in the UI
* Work with validation and disabled states

## Screenshots

Image

## Environment

* **Zard UI Version:** 1.0.0-beta.26
* **Angular Version:** 19
* **Browser & Version:** Brave 1.84.141 Chromium: 142.0.7444.176
* **Operating System:** macOS Sonoma

## Relevant Logs & Errors

```bash
ERROR RuntimeError: NG01203: No value accessor for form control name: 'date'.
Find more at https://angular.dev/errors/NG01203
    at _throwMissingValueAccessorError (forms.mjs:3523:9)
```

## Possible Fix

`z-date-picker` must implement Angular’s `ControlValueAccessor` and provide the `NG_VALUE_ACCESSOR`:

```ts
providers: [
  {
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => ZardDatePickerComponent),
    multi: true,
  },
],
```

And implement:

* `writeValue()`
* `registerOnChange()`
* `registerOnTouched()`
* `setDisabledState()`

This will allow the component to be used with both reactive and template-driven forms.

## Additional Context

Other Zard UI components (inputs, selects, etc.) already work with forms.
Adding `NG_VALUE_ACCESSOR` support would make `z-date-picker` consistent and usable in real applications that rely on reactive forms.

### PR DESCRIPTION
**Pull request by ribeiromatheuss**
## What was done? 📝
- Expand the year range using the min and max date validators
- Centralization of the calendar
- Validation of date input values

## Link to Issue 🔗
closes #346 

## Type of change 🏗

- [x] New feature (non-breaking change that adds functionality)
- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (non-breaking change that improves the code or technical debt)
- [ ] Chore (none of the above, such as upgrading libraries)

## Checklist 🧐

- [x] Tested on Chrome
- [ ] Tested on Safari
- [x] Tested on Firefox
- [x] No errors in the console

## Summary by CodeRabbit

* **Style**
  * Adjusted calendar grid classes for improved centering and visual alignment.

* **Refactor**
  * Year selector now derives available years from configured min/max dates for accurate navigation boundaries.
  * Centralized date normalization to ensure consistent behavior across single, multiple, and range selections and emissions.

* **New Features**
  * Added a demo showcasing expanded year-selection range.

* **Documentation**
  * API docs updated with min/max date details, selection modes, outputs, and a navigation reset method.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: libs/zard/src/lib/components/calendar/calendar-navigation.component.ts [hunk 1]
```diff
@@ -90,9 +90,10 @@ export class ZardCalendarNavigationComponent {
   protected readonly navClasses = computed(() => mergeClasses(calendarNavVariants()));
 
   protected readonly availableYears = computed(() => {
-    const currentYear = new Date().getFullYear();
+    const minYear = this.minDate()?.getFullYear() ?? new Date().getFullYear() - 10;
```
Comment (mikij) [inline libs/zard/src/lib/components/calendar/calendar-navigation.component.ts:83]: Explain this behavior to the API documentation of minDate and maxDate validators. Add or update one of demos to demonstrate this.

**Review by mikij — CHANGES_REQUESTED** [review]

File: libs/zard/src/lib/components/calendar/calendar-navigation.component.ts (hunk 1 above)
Comment (mikij) [reply libs/zard/src/lib/components/calendar/calendar-navigation.component.ts:83]: I also see these files chnaged after npm start and if any demo is resaved in your branch. Include them in your PR. Checked functionality LGTM
image

**Review by srizzon — APPROVED** [review]
Nice!

**Review by mikij — DISMISSED** [review]
LGTM
