### PR TITLE
🐛 fix(tree): emit zNodeClick on mouse click and refine node spacing

### LINKED ISSUE #451: [Bug] Tree: zNodeClick not emitted on mouse click + spacing issues
## Description

The `(zNodeClick)` output on `z-tree` does not emit when a node is clicked with the mouse. It only fires via keyboard (Enter key). This is because `ZardTreeNodeComponent.onContentClick()` calls `treeService.select()` but never notifies the parent `ZardTreeComponent` to emit the output.

Additionally, the tree node sizing has minor alignment issues:
- Toggle button and leaf spacer are different sizes (h-6 vs should be h-4)
- Checkbox alignment is off without a wrapper span
- Default icon has redundant `mr-1.5` when `gap-2` already handles spacing

## Steps to Reproduce

1. Use `z-tree` with `(zNodeClick)="handler($event)"`
2. Click any node with the mouse
3. The handler is never called

## Expected Behavior

`(zNodeClick)` should emit the clicked `TreeNode` on both mouse click and keyboard Enter.

## Fix

- Added `clickedNode` signal + `notifyNodeClick()` to `ZardTreeService` as a communication channel
- `ZardTreeNodeComponent.onContentClick()` now calls `notifyNodeClick()`
- `ZardTreeComponent` watches the signal via `effect()` and emits `zNodeClick`
- Added `onEnterKey()` with `stopPropagation()` to prevent double-fire
- Fixed toggle/spacer sizing and checkbox alignment

### PR DESCRIPTION
**Pull request by neopavan**
## Summary

Closes #451

- **Bug fix:** `(zNodeClick)` was only emitted via keyboard Enter, never on mouse click. Added a `clickedNode` signal in `ZardTreeService` as a notification channel from `ZardTreeNodeComponent` → `ZardTreeComponent`, with an effect that emits the output.
- **Spacing:** Reduced toggle/spacer from `h-6/w-6` to `h-4/w-4`, wrapped checkbox in alignment span, removed redundant `mr-1.5` from default icon since `gap-2` handles spacing.

## Changed files

| File | Change |
|------|--------|
| `tree.service.ts` | Added `clickedNode` signal + `notifyNodeClick()` |
| `tree.component.ts` | Added effect watching `clickedNode` → emits `zNodeClick` |
| `tree-node.component.ts` | `onContentClick` calls `notifyNodeClick`, added `onEnterKey` with `stopPropagation`, checkbox wrapper, sizing fixes |
| `tree.variants.ts` | Toggle `h-6 w-6` → `h-4 w-4` |

## Test plan

- [ ] Click a tree node with mouse → `(zNodeClick)` handler fires
- [ ] Press Enter on focused node → fires once (no double-fire)
- [ ] Checkable tree: checkboxes align with toggle chevrons
- [ ] Leaf nodes (no children) align with expandable nodes
- [ ] Virtual scroll mode still works
- [ ] Keyboard navigation (ArrowUp/Down/Left/Right, Home/End) still works

## Summary by CodeRabbit

* **Visual Updates**
  * More compact toggle and placeholder sizing
  * Tighter spacing around checkboxes and icons

* **Interaction Improvements**
  * Enter-key activation now stops propagation for cleaner keyboard behavior
  * Node-click notifications added so clicks and programmatic activations consistently propagate within the tree

* **Documentation**
  * Added docs page for the tree component to prerendered routes

### CODE REVIEW

File: libs/zard/src/lib/shared/components/tree/tree-node.component.ts [hunk 1]
```diff
@@ -46,18 +46,19 @@ import {
           <z-icon zType="chevron-right" class="size-4" />
         </button>
       } @else {
-        <span class="inline-flex h-6 w-6 shrink-0"></span>
+        <span class="inline-flex h-4 w-4 shrink-0"></span>
```
Comment (mikij) [inline libs/zard/src/lib/shared/components/tree/tree-node.component.ts]: use size-4 instead of h-4 w-4

File: libs/zard/src/lib/shared/components/tree/tree-node.component.ts [hunk 2]
```diff
@@ -68,13 +69,13 @@ import {
         role="treeitem"
         [attr.aria-selected]="isSelected()"
         (click)="onContentClick()"
-        (keydown.enter)="onContentClick()"
+        (keydown.enter)="onEnterKey($event)"
```
Comment (mikij) [inline libs/zard/src/lib/shared/components/tree/tree-node.component.ts]: you can also use (keydown.enter.stop) and remove event.stopPropagation() from method. That is our invention to reduce boilerplate code

File: libs/zard/src/lib/shared/components/tree/tree.variants.ts [hunk 3]
```diff
@@ -18,7 +18,7 @@ export const treeNodeVariants = cva('flex flex-col', {
 });
 
 export const treeNodeToggleVariants = cva(
-  'inline-flex h-6 w-6 shrink-0 items-center justify-center rounded-sm transition-transform duration-200 hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
+  'inline-flex h-4 w-4 shrink-0 items-center justify-center rounded-sm transition-transform duration-200 hover:bg-accent focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring',
```
Comment (mikij) [inline libs/zard/src/lib/shared/components/tree/tree.variants.ts]: size-4

**Review by mikij — CHANGES_REQUESTED** [review]

File: libs/zard/src/lib/shared/components/tree/tree-node.component.ts (hunk 1 above)
Comment (neopavan) [reply libs/zard/src/lib/shared/components/tree/tree-node.component.ts]: Addressed.

File: libs/zard/src/lib/shared/components/tree/tree-node.component.ts (hunk 2 above)
Comment (neopavan) [reply libs/zard/src/lib/shared/components/tree/tree-node.component.ts]: Addressed.

File: libs/zard/src/lib/shared/components/tree/tree.variants.ts (hunk 3 above)
Comment (neopavan) [reply libs/zard/src/lib/shared/components/tree/tree.variants.ts]: Addressed.
