### PR TITLE
🐛 fix(progress): progress container classes fix

### LINKED ISSUE #366: [Bug] progress component uses wrong classes
## 🐞 Bug Description

Inspecting the shadcn/ui progress and compering with corresponding Zard component noticed they are not using same tailwindCSS classes so look of ZardUI is not at the best. Also I can't see difference between default and circle shapes, so I will remove circle.

## 🔄 Steps to Reproduce

1. Pay attention to progress background
2. It should be more visible like in shadcn variant

## 📷 Expected Behavior

Progress bar background area should be clearly visible

## 🖥️ Screenshots

Image

## 🏗️ Environment

- **Zard UI Version:** latest
- **Angular Version:** any
- **Browser & Version:** any
- **Operating System:** any

## 📜 Relevant Logs & Errors

no errors

```bash
Paste logs here
```

## 🛠️ Possible Fix

apply the same classes as shdcn

### PR DESCRIPTION
**Pull request by mikij**
## What was done? 📝

Changed classes responsible for progress container. Removed circle shape variant as it looks exactly the same as default (no visual differences).

## Screenshots or GIFs 📸

|-----Old-----|
image
|-----Implementation-----|
image

## Link to Issue 🔗

Closes #366 

## Type of change 🏗

- [ ] New feature (non-breaking change that adds functionality)
- [x] Bug fix (non-breaking change that fixes an issue)
- [ ] Refactor (non-breaking change that improves the code or technical debt)
- [ ] Chore (none of the above, such as upgrading libraries)

## Checklist 🧐

- [x] Tested on Chrome
- [ ] Tested on Safari
- [ ] Tested on Firefox
- [x] No errors in the console

## Summary by CodeRabbit

* **New Features**
  * Added zIndeterminate property to enable an indeterminate (loading) progress state.

* **Updates**
  * Removed the 'circle' shape — progress bars now support 'default' and 'square' shapes.
  * Adjusted default visual styling and type/size behavior for progress bars, affecting their appearance and animations.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: libs/zard/src/lib/components/progress-bar/progress-bar.component.ts
Comment (ribeiromatheuss) [inline libs/zard/src/lib/components/progress-bar/progress-bar.component.ts:1]: If the value of zIndeterminate is a boolean, use { transform: booleanAttribute } to accept the simple form

Comment (mikij) [reply libs/zard/src/lib/components/progress-bar/progress-bar.component.ts:1]: ok done

File: libs/zard/src/lib/components/progress-bar/demo/shape.ts [hunk 1]
```diff
@@ -1,14 +1,13 @@
...
 @Component({
   selector: 'z-demo-progress-bar-shape',
   imports: [ZardProgressBarComponent],
-  standalone: true,
   template: `
-    <z-progress-bar [progress]="50" zShape="default" />
-    <z-progress-bar [progress]="50" zShape="circle" />
+    <z-progress-bar [progress]="50" zShape="default" zType="destructive" />
+    <z-progress-bar [progress]="50" zType="accent" />
     <z-progress-bar [progress]="50" zShape="square" />
```
[the remark this answers is not in the document]
Comment (mikij) [reply libs/zard/src/lib/components/progress-bar/demo/shape.ts:11]: this is just done by purpose to show at least somewhere destructive type of progress
